# Generated by Django 4.1.3 on 2022-12-23 14:03

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_experience_began', models.DateField()),
                ('icon_name', models.CharField(max_length=50)),
                ('base_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year_of_realization', models.IntegerField()),
                ('time_invested', models.CharField(max_length=50)),
                ('project_link', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.PositiveSmallIntegerField(choices=[('1', 'Personal'), ('2', 'Professional')], default='1')),
                ('technologies', models.ManyToManyField(related_name='projects', to='projects.technology')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mediafiles', validators=[projects.models.validate_is_image])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='projects.project')),
            ],
        ),
    ]
